#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::KProgressHUD.Resource.Color.kprogresshud_default_color = global::Sample.Resource.Color.kprogresshud_default_color;
			global::KProgressHUD.Resource.Color.kprogresshud_grey_color = global::Sample.Resource.Color.kprogresshud_grey_color;
			global::KProgressHUD.Resource.Drawable.kprogresshud_spinner = global::Sample.Resource.Drawable.kprogresshud_spinner;
			global::KProgressHUD.Resource.Id.background = global::Sample.Resource.Id.background;
			global::KProgressHUD.Resource.Id.container = global::Sample.Resource.Id.container;
			global::KProgressHUD.Resource.Id.details_label = global::Sample.Resource.Id.details_label;
			global::KProgressHUD.Resource.Id.label = global::Sample.Resource.Id.label;
			global::KProgressHUD.Resource.Layout.kprogresshud_hud = global::Sample.Resource.Layout.kprogresshud_hud;
			global::KProgressHUD.Resource.String.ApplicationName = global::Sample.Resource.String.ApplicationName;
			global::KProgressHUD.Resource.String.Hello = global::Sample.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int kprogresshud_default_color = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int kprogresshud_grey_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int my_blue = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int my_gray = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int my_green = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int my_purple = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int frame_001 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int frame_002 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int frame_003 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int frame_004 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int frame_005 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int frame_006 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int frame_007 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int frame_008 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int frame_009 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int frame_010 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int frame_011 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int frame_012 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int frame_013 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int frame_014 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int frame_015 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int frame_016 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int frame_017 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int frame_018 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int frame_019 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int frame_020 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int kprogresshud_spinner = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int spin_animation = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int background = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int btn1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int btn2 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int btn3 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int btn4 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int btn5 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int btn6 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int btn7 = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int container = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int details_label = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int label = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int selected = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int kprogresshud_hud = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
